### ISSUE TITLE
Passing incorrect evidence keys gives misleading/unhelpful error message

### ISSUE THREAD

**Issue by stuartlangridge** [51Degrees/location-node#1]
If evidence is added to flowData with a non-existent evidence key then no useful error message is generated.

```javascript
const FiftyOneDegreesGeoLocation = require('./index');
let localResourceKey = 'AQQNX4toap2oMURt2Eg';
const pipeline = new FiftyOneDegreesGeoLocation.GeoLocationPipelineBuilder({
  resourceKey: localResourceKey
}).build();
pipeline.on('error', err => { console.error("woo", err)});

const getCountry = async function (latitude, longitude) {
  const flowData = pipeline.createFlowData();
  flowData.evidence.add('query.NOT_EXISTENT_KEY', latitude);
  flowData.evidence.add('query.51D_Pos_longitude', longitude);
  await flowData.process();
  if (!flowData.location.country.hasValue) { // expected to be false
    console.log(flowData.location.country.noValueMessage); 
  }
/*
This property requires evidence values from JavaScript running on the client.
It cannot be populated until a future request is made that contains
this additional data.
*/
};

getCountry('51', '-1');
```

Note that this is problematic in two ways; it does not identify which data was required and not provided, and it does not identify which key was incorrect.

The library retrieves a list of permitted keys from https://cloud.51degrees.com/api/v4/evidencekeys before making the API call, so it should be possible to check the passed keys against the permitted keys and flag an erroneous key on the client side without making the API call.

The API could also return a specific list of which keys were required, rather than a generic error message explaining that data was missing without specifying _which_ data was missing, but this may require extra work on the server side.

**Comment by stuartlangridge** [comment]
Investigating this issue, in https://github.com/51Degrees/pipeline-node/blob/875cbfe1fec0bab5d5569e531bb019a42c871b70/fiftyone.pipeline.cloudrequestengine/cloudRequestEngine.js#L172 an `evidence` object is created, and `engine.evidenceKeyFilter` has already been set, and calling `engine.evidenceKeyFilter.filterEvidence(evidence)` on the `evidence` object containing `query.NOT_EXISTENT_KEY` does correctly filter that key out. However, this isn't called; I'm not sure whether `filterEvidence` is _supposed_ to be called before making the HTTP request. If it is supposed to be called, then it isn't being. If it's not supposed to be called, then adding a call to `filterEvidence` inside `getData` might be a good idea, especially if a warning could be issued to show which keys were filtered (because they are incorrect) so that the developer can track down the problem. (The API should not just silently filter out unknown keys without some form of warning, otherwise the developer will have no idea that it's happening.) I'm happy to write a PR to add this if someone can confirm whether and where `filterEvidence` is _meant_ to be used.

**Comment by tungntpham** [comment]
Hi @stuartlangridge . Many thanks. In this scenario:

1.	A caller can add any evidence keys with any values. There is no error we can throw at that point.
2.	The filters will restrict the evidence an element receives to only those values that can affect its output (or that it wants for some other purpose). 
3.	Individual engines should return errors if there is no relevant evidence or not enough evidence.

Thus, the existing error message should be sufficient in the context of location engine.
