### ISSUE TITLE
Deprecated Jest version.

### ISSUE THREAD

**Issue by tungntpham** [51Degrees/location-node#8]
The Jest and Jest-unit versions are deprecated. However no warnings was raised for this project as specified in this [issue](https://github.com/51Degrees/pipeline-node/issues/4).

However, since the version is deprecated, it should be address here as well. The same issue might be encountered when the version is updated as specified in the referenced issue.

**Comment by ben51degrees** [comment]
Closed in [version 4.3.3](https://github.com/51Degrees/location-node/releases/tag/4.3.3)
